-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 11:25:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cursostecnologicos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cursostecnologicos` ;

-- -----------------------------------------------------
-- Schema cursostecnologicos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cursostecnologicos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cursostecnologicos` ;

-- -----------------------------------------------------
-- Table `cursostecnologicos`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(10) NULL DEFAULT NULL,
  `contra` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `cursostecnologicos`.`admins` (`usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cursostecnologicos`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(10) NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cursostecnologicos`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`cursos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL DEFAULT NULL,
  `horario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `FK_cursos_horario`
    FOREIGN KEY (`horario`)
    REFERENCES `cursostecnologicos`.`horario` (`idHorario`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `cursostecnologicos`.`cursos` (`nombre` ASC) VISIBLE;

CREATE INDEX `FK_cursos_horario` ON `cursostecnologicos`.`cursos` (`horario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cursostecnologicos`.`tipopersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`tipopersona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cursostecnologicos`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificación` INT NOT NULL,
  `nombre` VARCHAR(25) NULL DEFAULT NULL,
  `apellido` VARCHAR(25) NULL DEFAULT NULL,
  `edad` INT NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `cursoAsignado` INT NULL DEFAULT NULL,
  `tipoPersona` INT NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_personas_cursoa`
    FOREIGN KEY (`cursoAsignado`)
    REFERENCES `cursostecnologicos`.`cursos` (`codigo`),
  CONSTRAINT `FK_personas_tipopersona`
    FOREIGN KEY (`tipoPersona`)
    REFERENCES `cursostecnologicos`.`tipopersona` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `identificación_UNIQUE` ON `cursostecnologicos`.`personas` (`identificación` ASC) VISIBLE;

CREATE INDEX `FK_personas_tipopersona` ON `cursostecnologicos`.`personas` (`tipoPersona` ASC) VISIBLE;

CREATE INDEX `FK_personas_cursoa` ON `cursostecnologicos`.`personas` (`cursoAsignado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cursostecnologicos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursostecnologicos`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(10) NULL DEFAULT NULL,
  `contra` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `cursostecnologicos`.`users` (`usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
